sudo: false # Migrating from legacy to container-based infrastructure for Travis
            # Ref: http://docs.travis-ci.com/user/migrating-from-legacy/
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"